### ISSUE TITLE
Does queueing favorites that are playlists work for you?

### ISSUE THREAD

**Issue by maddox** [rob-howard/sonos-objc-fork#1]
👋 I found your fork while working on a Sonos project using the base lib. I was mostly interested in queuing favorites. I was able to use your additions to fetch favorites, and queue favorites that are "stations", but any favorites that are "playlists", be it from Spotify, Apple Music, or even a Sonos playlist, fails.

I'm curious if you're still using this, and if it is something that you know works or at least worked at one point. 

Thanks so much!

**Comment by rob-howard** [comment]
Hi Jon,  I'm personally not using this anymore since sonos has more deep alexa integration built in.  When it was working, I really only used it to queue up my pandora favorite stations.   So I haven't tried it with much content.  If I were to try to get them to work, I would take a look at wireshark or a similar network monitoring tool to see how the requests are getting passed around to the controllers and mimic that.

**Comment by maddox** [comment]
I figured it out! You can't `play` favorites that are playlists. You have to `queue` them with the API. After doing that, and some other fixes like a method that focuses the queue to play from it, it worked.

Thanks!
